version: '3'

services:
  server:
    build: server/
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres

  migrate:
    image: cartrax-server
    build: server/
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres
    command: ["./cartrax", "migrate"]
    restart: on-failure
    depends_on:
      - postgres

  dbadmin:
    image: adminer
    restart: always
    ports: 
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  postgres:
    environment:
      POSTGRES_PASSWORD: password
  client:
    build: client/ 
