version: '3'

services:
  server:
    build: server/
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: postgres

  postgres:
    environment:
      POSTGRES_PASSWORD: password
  client:
    build: client/ 
