#!/bin/bash

function postgres {
    postgresCount=$(docker ps | grep postgres | wc -l)
    target=1
    if [ $postgresCount -ne $target ]; then
        docker run \
            --name cartrax-postgres \
            --hostname cartrax-postgres \
            -e POSTGRES_PASSWORD=password \
            -dp 5432:5432 \
            postgres:latest
    fi
}

postgres

case "$1" in
    release) cargo run --release;;
    doc) cargo doc --open;;
    dev) cargo run;;
esac
